FROM ubuntu:latest
# Actualiza  e instala Apache2
RUN apt-get update && \
    apt-get install -y apache2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Configura Apache para que se ejecute en primer plano y establece el ServerName
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# módulos necesarios
RUN a2enmod proxy && \
    a2enmod proxy_http && \
    a2enmod proxy_balancer &&  \
    a2enmod lbmethod_byrequests

# Exponer el puerto 80 
EXPOSE 80



# Iniciar Apache 
CMD ["apache2ctl", "-D", "FOREGROUND"]

